fix: avoid missing unit warning on purge
Signed-off-by: Jingxiang Zhang <jingzhang@nvidia.com>

diff --git a/deployments/packages/scripts/postrm b/deployments/packages/scripts/postrm
--- a/deployments/packages/scripts/postrm
+++ b/deployments/packages/scripts/postrm
@@ -2,11 +2,16 @@
 set -e
 
 disable_fleetintd() {
-    if [ -d /run/systemd/system ]; then
+    rm -f /etc/systemd/system/multi-user.target.wants/fleetintd.service 2>/dev/null || echo "[WARNING] Failed to remove service enablement symlink"
+
+    if [ -d /run/systemd/system ] && {
+        [ -e /etc/systemd/system/fleetintd.service ] ||
+        [ -e /run/systemd/system/fleetintd.service ] ||
+        [ -e /usr/lib/systemd/system/fleetintd.service ] ||
+        [ -e /lib/systemd/system/fleetintd.service ]
+    }; then
         systemctl disable fleetintd.service || echo "[WARNING] Failed to disable service"
     fi
-
-    rm -f /etc/systemd/system/multi-user.target.wants/fleetintd.service 2>/dev/null || echo "[WARNING] Failed to remove service enablement symlink"
 }
 
 case "$1" in
